### ISSUE TITLE
ya-malware-block.sh: Deleting obsolete Blocks when ip count goes below 65k

### ISSUE THREAD

**Issue by 0crap** [shounak-de/misc-scripts#1]
When block IP count goes above 65k YAMalwareBlock2IP etc. is created. BUT, when other days IP count stays below 65k those YAMalwareBlock2IP, ...3IP etc. sets are still active in drop chain and ipset.
They don't get deleted.
This can result in false positives.

This can be fixed by adding below code.
Put code in between the "esac" and "startTS" command to the ya-malware-block.sh script.

`# Delete old YAMalwareBlock rules.`
`logger -t Firewall "Delete old YAMalwareBlock rules."`
`echo Delete old YAMalwareBlock rules.`
`iptables -t raw -L --line-numbers | grep YAMalwareBlock | cut -d' ' -f1 | sed '1!G;h;$!d' | while read number; do iptables -t raw -D PREROUTING $number; done`
`ipset -L | grep YAMalwareBlock | cut -d' ' -f2 | while read setname; do ipset --destroy $setname; done`

**Comment by shounak-de** [comment]
This will blindly delete the iptables rule and destroy the sets each time. For most use cases, this is not desired (the refresh process will take care of that automatically).

However, for those who edit their ya-malware-block.urls file frequently, such that they have a changing set count, the commit 6f76cfe613059914af892723becc4d8919a8d861 should take care of it.
