### ISSUE TITLE
create-ipset-lists.sh: When the router stays on a long time, without reboot, country blocking never gets updated.

### ISSUE THREAD

**Issue by 0crap** [shounak-de/misc-scripts#2]
Running the script as a cron job will never update country blocking.
It seems because ipset and/or iptables are already in place and the script exits.

I fixed it with below code just above the "# Country blocking by nethashes ..." comment line:

`# Delete old BlockedCountries`
`logger -t Firewall "Delete old BlockedCountries."`
`iptables --list INPUT --line-numbers | grep BlockedCountries | cut -d' ' -f1 | while read number; do iptables -D INPUT $number; done`
`ipset -L | grep BlockedCountries | cut -d' ' -f2 | while read setname; do ipset --destroy $setname; done`

It works fine on my RT-N66U but makes the original check that prevent the lists from being loaded if they are already loaded ... kind of obsolete.
(I think that check can safely be removed if above code is implemented.)

**Comment by shounak-de** [comment]
Fixed in commit 685975720334cb82c1d3a7df1078fd523f3b123e
